---
name: latest-release

on:
  push:
    branches:
      - main

jobs:
  pre-release:
    name: Latest Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          automatic_release_tag: latest
          prerelease: false
          title: Latest
          files: |-
            action.yml
            LICENSE
            README.md
